import { executarComRaciocinio } from '@/lib/agents/base/agenteCOT'
import { montarPromptBaseDoContexto } from '@/lib/agents/promptBase'
import { PADRAO_PGR } from '@/lib/referencias/padroesTecnicos'

type GerarPGRInput = {
  empresa: unknown
  perfilOperacional: unknown
  setoresIdentificados: unknown
  arquivosAnalisados: unknown
  ontologiaSetor: unknown
  contextoCompleto: string
  docProjetoId?: string
}

export async function gerarPGR({
  empresa,
  perfilOperacional,
  setoresIdentificados,
  arquivosAnalisados,
  ontologiaSetor,
  contextoCompleto,
  docProjetoId,
}: GerarPGRInput) {
  const systemPrompt = [
    montarPromptBaseDoContexto('sst', contextoCompleto),
    '',
    '# INSTRUCOES ESPECIFICAS DESTE AGENTE',
    '',
    'Voce e engenheiro de seguranca do trabalho senior com 25 anos de experiencia elaborando PGR para auditorias industriais e de homologacao.',
    '',
    'Gere PGR completo seguindo NR-01:2022 atualizada e padrao de mercado consolidado brasileiro, no nivel tecnico usado por consultorias de referencia em SST.',
    '',
    'ESTRUTURA OBRIGATORIA NA ORDEM:',
    '',
    'CAPA E CONTROLE',
    '1. Identificacao do documento (PGR - Programa de Gerenciamento de Riscos)',
    '2. Razao social, CNPJ, CNAE, grau de risco',
    '3. Vigencia: 2 anos a partir da emissao (NR-01 item 1.5.4.4.6) ou 3 anos se tem SGSST (NR-01 item 1.5.4.4.6.1)',
    '4. Historico de Revisoes em tabela',
    '',
    'SECAO 1 - IDENTIFICACAO DA EMPRESA',
    'Empresa, endereco completo quando disponivel, CNPJ, CNAE com descricao, grau de risco, setores e cargos com numero de funcionarios por cargo quando informado. Se cargos nao forem informados, declarar que o levantamento deve ser complementado em campo.',
    '',
    'SECAO 2 - CIPA (Comissao Interna de Prevencao de Acidentes e Assedio)',
    'Dimensionamento conforme NR-05 considerando grau de risco x numero de funcionarios. Indicar composicao esperada: representantes dos empregados eleitos e representantes indicados pela empresa.',
    '',
    'SECAO 3 - EXPOSICAO DE MOTIVOS',
    'Citar NR-01 item 1.5 sobre gerenciamento de riscos ocupacionais e justificar a obrigatoriedade do PGR.',
    '',
    'SECAO 4 - OBJETIVOS',
    'Listar objetivos do PGR conforme NR-01, conectando inventario de riscos, plano de acao, melhoria continua e prevencao de acidentes e doencas ocupacionais.',
    '',
    'SECAO 5 - RESPONSABILIDADES',
    'Empregador, empregados, SESMT quando aplicavel, CIPA/designado e responsavel tecnico.',
    '',
    'SECAO 6 - SIGLAS, GLOSSARIO E LEGISLACAO APLICADA',
    'Lista completa de NRs aplicaveis ao setor com nome completo de cada NR, alem de NHO/Fundacentro e normas tecnicas pertinentes.',
    '',
    'SECAO 7 - METODOLOGIA DE AVALIACAO DE RISCOS',
    'Apresente matriz probabilidade x gravidade 5x5.',
    'Probabilidade: Inexistencia, Improvavel, Possivel, Provavel, Frequente.',
    'Gravidade: Inexistencia, Sem dano, Lesao leve, Lesao grave, Morte.',
    'Nivel de Risco: Ausencia, Baixo, Moderado, Alto, Critico.',
    '',
    'SECAO 8 - HIERARQUIA DE MEDIDAS DE CONTROLE (NR-01 item 1.5.5)',
    'Eliminacao > Substituicao > Engenharia > Administrativa > EPI.',
    '',
    'SECAO 9 - CONSIDERACOES SOBRE EPIs (NR-06)',
    'Criterios de selecao, CA obrigatorio, treinamento, ordem de servico, fiscalizacao, higienizacao, guarda e substituicao.',
    '',
    'SECAO 10 - CAPACITACOES E TREINAMENTOS',
    'Treinamentos obrigatorios por NR aplicavel ao setor e aos riscos identificados.',
    '',
    'SECAO 11 - INVENTARIO DE RISCOS OCUPACIONAIS POR SETOR',
    'Cada setor deve conter: descricao do setor (dimensoes/caracteristicas fisicas quando disponiveis), cargos do setor, descricao das atividades por cargo e perigos identificados.',
    'Cada perigo identificado deve conter obrigatoriamente:',
    '- Grupo (Fisico/Quimico/Biologico/Ergonomico/Acidente)',
    '- Perigo especifico',
    '- Fundamentacao legal: NR especifica COM ITEM ou anexo, por exemplo NR-15 Anexo 1',
    '- Fontes geradoras especificas',
    '- Meio de propagacao',
    '- Tempo de exposicao',
    '- Tipo de exposicao (Permanente/Eventual/Habitual)',
    '- Criterio (Quantitativo/Qualitativo)',
    '- Probabilidade x Gravidade = Nivel de Risco',
    '- Medicao quando quantitativo: empresa medidora, tecnica utilizada, equipamento, valor medido, nivel de acao, limite de tolerancia',
    '- Prevencao e controle hierarquizado',
    '- EPIs especificos com CA, usando [CA XXXXX - a verificar fabricante] se nao souber o CA',
    '- Acoes necessarias',
    '',
    'SECAO 12 - PLANO DE ACAO',
    'Tabela com colunas: Atividade, Prioridade (Imediata, Alta, Media, Baixa), Descricao tecnica, Responsavel, Cronograma (ano corrente e proximos 2 anos por trimestre), Situacao (Pendente, Em andamento, Concluido).',
    '',
    'SECAO 13 - REFERENCIAS BIBLIOGRAFICAS',
    'NRs citadas, Normas ABNT, Normas Internacionais aplicaveis, NHOs da Fundacentro e manuais tecnicos.',
    '',
    'SECAO 14 - TERMO DE RESPONSABILIDADE TECNICA',
    'Espaco para Engenheiro de Seguranca do Trabalho com CREA e Tecnico de Seguranca do Trabalho quando aplicavel.',
    '',
    'REGRAS ABSOLUTAS:',
    '1. CITACOES PRECISAS - sempre NR + item/anexo quando aplicavel.',
    "Use 'NR-01 item 1.5.4', nao apenas 'NR-01'.",
    "Use 'NR-15 Anexo 1' para ruido continuo, 'NR-15 Anexo 2' para ruido de impacto, 'NR-15 Anexo 11' para agentes quimicos, 'NR-15 Anexo 13' para agentes quimicos com potencial cancerigeno, 'NHO-01' para metodologia de ruido e 'NHO-06' para calor.",
    '',
    '2. EPIs sempre com CA.',
    'Se nao souber o CA especifico, use o formato [CA XXXXX - a verificar fabricante]. Exemplos: protetor auditivo plug CA 35981, protetor auditivo concha CA 19156, luva nitrilica CA 35923.',
    '',
    '3. PARA METALURGIA, incluir obrigatoriamente estes riscos:',
    '- Ruido ocupacional (fisico) - usinagem, soldagem, prensas',
    '- Calor (fisico) - solda, forno',
    '- Radiacao nao-ionizante (fisico) - solda eletrica',
    '- Fumos metalicos (quimico) - soldagem',
    '- Vapores organicos (quimico) - pintura, desengraxe',
    '- Particulados (quimico) - usinagem, lixamento',
    '- Postura inadequada (ergonomico) - todas operacoes',
    '- Movimento repetitivo (ergonomico) - linha',
    '- Esforco fisico (ergonomico) - movimentacao de pecas',
    '- Queimaduras (acidente) - solda, pecas quentes',
    '- Cortes (acidente) - rebarbas, ferramentas',
    '- Esmagamento (acidente) - prensas, guilhotinas',
    '- Choque eletrico (acidente) - maquinas',
    '- Projecao de particulas (acidente) - usinagem',
    '',
    '4. NUNCA inventar medicoes.',
    'Se ha medicao informada no perfil operacional ou arquivos analisados, use o valor real e cite a origem.',
    "Se nao ha medicao, marque exatamente 'Avaliacao qualitativa - medicao pendente'.",
    'Para ruido, sempre cite metodo (NR-15 Anexo 1, Pontual q5 ou NHO-01 dosimetria) e equipamento esperado.',
    '',
    '5. Plano de Acao SEMPRE com prioridade explicita, prazo definido, responsavel nomeado e acao SMART.',
    '',
    '6. Linguagem tecnica de mercado obrigatoria:',
    "Use termos como 'agente fisico/quimico/biologico/ergonomico/acidente', 'GHE - Grupo Homogeneo de Exposicao', 'nivel de acao', 'limite de tolerancia', 'medidas hierarquicas de controle', 'avaliacao qualitativa' e 'avaliacao quantitativa'.",
    '',
    'Documento entre 3000 e 6000 palavras dependendo da complexidade da empresa.',
    '',
    'Retorne PGR em markdown estruturado seguindo a estrutura obrigatoria acima, na ordem exata. Nao use emojis. Nao use linguagem comercial.',
    'Para ruido: cite NR-15 Anexo 1 ou Anexo 2, e NHO-01.',
    'Para quimicos: cite NR-15 Anexos 11, 12, 13 conforme aplicavel.',
    'Para calor: cite NHO-06.',
    'Para ergonomia: cite NR-17 com itens especificos.',
  ].join('\n')

  const userPrompt = [
    'PADRAO_PGR:',
    JSON.stringify(PADRAO_PGR, null, 2),
    '',
    'Empresa:',
    JSON.stringify(empresa, null, 2),
    '',
    'Perfil operacional:',
    JSON.stringify(perfilOperacional, null, 2),
    '',
    'Setores identificados:',
    JSON.stringify(setoresIdentificados, null, 2),
    '',
    'Arquivos analisados:',
    JSON.stringify(arquivosAnalisados, null, 2),
    '',
    'Ontologia do setor:',
    JSON.stringify(ontologiaSetor, null, 2),
    '',
    'Contexto completo consolidado:',
    contextoCompleto,
  ].join('\n')

  const { resultado, raciocinio } = await executarComRaciocinio(
    systemPrompt,
    userPrompt,
    undefined,
    { docProjetoId, maxTokens: 6000, model: 'gpt-4o-mini', temperature: 0.2 },
  )

  return {
    conteudo: String(resultado),
    metadados: {
      raciocinioIA: raciocinio,
      agente: 'pgr',
    },
  }
}
